version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=bot
      - COUCHDB_PASSWORD=bot
    volumes:
      - ./dbdata:/Users/20084530/couchdb/data
