version: '3'

services:
  couchserver:
    image: couchdb
    networks:
      - my-net
    restart: always
    env_file: .env
    volumes:
      - /home/olegroom/couchdb/data:/opt/couchdb/data
    ports:
      - "5984:5984"
  credsaverbot:
    build:
      dockerfile: Dockerfile
    networks:
      - my-net
    env_file: .env
    environment:
      DB_URL: http://couchserver:5984

networks:
  my-net:
    driver: bridge